import React from 'react';
import { withStyles } from 'material-ui/styles';
import PropTypes from 'prop-types';
import { compose, withState } from 'recompose';

import DefaultGroupImage from '../../assets/group.png';
import DefaultUserImage from '../../assets/users.png';


//----------------------------------------------------
// PROVIDES HANDY PAGINATION 
//----------------------------------------------------
const withPaginator = (Component) =>
  class WithPaginator extends React.Component {

	static propTypes = {
    	pageSize: PropTypes.number,
  		store: PropTypes.object
   	};

   	static defaultProps = {
        pageSize: 8
   	};

    constructor(props) {
    	super(props);

		// console.log('paginator...');
		// console.log(props);
		// console.log('paginator done...');

		// SOME SIMULATED DATA
	    this.testList = [
	      { objectID : 0, title: 'hello', subTitle: 'sub', defaultImage: DefaultUserImage },
	      { objectID : 1, title: 'there', subTitle: 'sub', defaultImage: DefaultUserImage },
	      { objectID : 2, title: 'you', subTitle: 'sub', defaultImage: DefaultUserImage },
	      { objectID : 3, title: 'hello', subTitle: 'sub', defaultImage: DefaultUserImage },
	      { objectID : 4, title: 'there', subTitle: 'sub', defaultImage: DefaultUserImage },
	      { objectID : 5, title: 'you', subTitle: 'sub', defaultImage: DefaultUserImage },
	      { objectID : 6, title: 'hello', subTitle: 'sub', defaultImage: DefaultUserImage },
	      { objectID : 7, title: 'there', subTitle: 'sub', defaultImage: DefaultUserImage },
	      { objectID : 8, title: 'you', subTitle: 'sub', defaultImage: DefaultUserImage },
	      { objectID : 9, title: 'hello', subTitle: 'sub', defaultImage: DefaultUserImage },
	      { objectID : 10, title: 'there', subTitle: 'sub', defaultImage: DefaultUserImage },
	      { objectID : 11, title: 'you', subTitle: 'sub', defaultImage: DefaultUserImage },
	      { objectID : 12, title: 'hello', subTitle: 'sub', defaultImage: DefaultUserImage },
	      { objectID : 13, title: 'there', subTitle: 'sub', defaultImage: DefaultUserImage },
	      { objectID : 14, title: 'you', subTitle: 'sub', defaultImage: DefaultUserImage }
	    ];

		this.state = {
			loading: false,
			list: [],
			pageIndex: 0
		};
    }

    componentDidMount() {
    	// subscribe to whatever store is responsible for data
    	const { pageSize } = this.props;

    	this.setState({
    		list: this.testList.slice(0, pageSize)
    	});
    }

    componentWillUnmount() {
      // unsubscribe to whatever store is responsibe for data
    }

    onRequestNextPage = () => {
    	this.setState({
    		loading: true
    	});

    	// this should be generated by a store event
    	this.onRetrievedPage();
    }

    onRetrievedPage = () => {
    	console.log('retrieved next page');

    	const nextPage = this.state.pageIndex + 1;
    	this.setState({
    		loading: false,
    		pageIndex: nextPage,
    		list: this.state.list.concat(this.testList.slice(7, 10))
    	});
    }

    render() {
      return <Component 
      			loading={ this.state.loading } 
      			list={this.state.list} 
      			onPaginatedLoad={ this.onRequestNextPage }
      			{...this.props} />;
    }
  }

export default withPaginator;
